version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://root:root@db:3306/mydb
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
    volumes:
      - ./server:/app

volumes:
  db-data:
