version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  notification-service:
    build: .
    container_name: notification-service
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
